# Generated by Django 5.0.3 on 2024-03-06 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('specimen_origin', models.CharField(max_length=20)),
                ('submission_date', models.DateTimeField()),
                ('notes', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dna_sequence', models.TextField(max_length=500)),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnalab.specimen')),
            ],
        ),
    ]
