# Generated by Django 5.0.3 on 2024-03-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnalab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
