# Generated by Django 5.0.3 on 2024-03-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnalab', '0002_alter_sequence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
