# Generated by Django 5.0.3 on 2024-04-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnalab', '0003_alter_specimen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimen',
            old_name='specimen_origin',
            new_name='specimen_identifier',
        ),
    ]
