# Generated by Django 5.0.3 on 2024-04-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnalab', '0004_rename_specimen_origin_specimen_specimen_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specimen',
            old_name='specimen_identifier',
            new_name='specimen_id',
        ),
    ]
